### ISSUE TITLE
getConversations() has no _id value? 

### ISSUE THREAD

**Issue by mgladwell** [EverythingMe/easy-content-providers#4]
I don't know if that is part of android, but how would I go about getting around this issue?
Basically, I want to populate a listview with the conversations that are currently on the device.
I have made an adapter for the class, but I am getting the error that It has no _id value in the database.

Adapter Class: 
 public class testingAdapter extends CursorAdapter{
 public testingAdapter(Context context, Cursor cursor, int flag) {
        super(context, cursor, 0);
    }
    @Override
    public View newView(Context context, Cursor cursor, ViewGroup parent) {
        return LayoutInflater.from(context).inflate(
                R.layout.conversationlist_row,
                parent,
                false
        );
    }

```
@Override
public void bindView(View view, Context context, Cursor cursor) {
    TextView contactName = (TextView) view.findViewById(R.id.contactname_conversationrow);
    TextView snippet = (TextView) view.findViewById(R.id.snippet_conversationrow);
    TextView itemnumber = (TextView) view.findViewById(R.id.itemnumber_conversationrow);
    // Getting the stuff from the cursor
    String contactNameString = "Testing";
    String Snippet = cursor.getString(cursor.getColumnIndexOrThrow("snippet"));
    String itemNumber = cursor.getString(cursor.getColumnIndexOrThrow("messageCount"));
    // Used for the other thing later
    int threadId = cursor.getInt(cursor.getColumnIndexOrThrow("thread_id"));
    // Setting the stuff
    contactName.setText(contactNameString);
    snippet.setText(Snippet);
    itemnumber.setText(itemNumber);
}`
```

The fragment that I am implementing it in:

`
Cursor cursor = telephonyProvider.getConversations().getCursor();

 ListView lvItems = (ListView)view.findViewById(R.id.conservationlistview);

```
    testingAdapter testingAdapter = new testingAdapter(getContext(), cursor, cursor.getCount());
    lvItems.setAdapter(testingAdapter)
```

`

Sorry for the bad formatting, I can't get it to paste properly.
Thanks in advanced; 
Morgan.

**Comment by sromku** [comment]
@TrappedDestiny please add a stacktrace with the error you get. TX

**Comment by mgladwell** [comment]
Here you go;

 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.urbanisation.testingsms/com.urbanisation.testingsms.MainActivity}: java.lang.IllegalArgumentException: column '_id' does not exist
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: column '_id' does not exist
            at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:303)
            at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:78)
            at android.widget.CursorAdapter.init(CursorAdapter.java:172)
            at android.widget.CursorAdapter.<init>(CursorAdapter.java:149)
            at com.urbanisation.testingsms.testingAdapter.<init>(testingAdapter.java:14)
            at com.urbanisation.testingsms.ConversationListFragment.onCreateView(ConversationListFragment.java:48)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
            at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:330)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:547)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1194)
            at android.app.Activity.performStart(Activity.java:5258)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2171)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
            at android.app.ActivityThread.access$800(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by sromku** [comment]
It's a bit strange, since `Conversation` doesn't require `_id`. It fails on line 14 of `testingAdapter` as it's shown in stacktrace. Can you show your line of code at this specific line?

**Comment by mgladwell** [comment]
Sure, As its in a class, I thought id post it aswell:

 Line 14 is : `super(context, cursor, 0);`
The class that It is referencing is as such:
`public testingAdapter(Context context, Cursor cursor, int flag) {
        super(context, cursor, 0);
    }`

**Comment by sromku** [comment]
Ok, so the issue is found. The `CursorAdapter` requires a column called `_id` always. This is internal implementation of Android. On other hand the `Conversation` table doesn't have this column, so it means, you can't use CursorAdapter. 
The solution will be using RecycleView instead of ListView and `RecyclerView.Adapter` and walk through Cursor inside. 
Check this sample implementation in the sample app: [here](https://github.com/EverythingMe/easy-content-providers/blob/master/app/src/main/java/me/everything/providers/sample/base/RecycleViewCursorFragment.java#L140)

**Comment by mgladwell** [comment]
Okay, Thanks.
